import Navbar from "@/components/navbar";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';

export const metadata = {
  title: "Teo's FileServer",
  description: "Generated by create next app",
};

export default function AuthLayout({ children, params }) {

  // console.log (params);

  return (
    <html lang="en">
      <body>
        {/* <Navbar /> */}
        {children}
      </body>
    </html>
  );
}
