import Navbar from "@/components/navbar";
import "../globals.css";
// import 'bootstrap/dist/css/bootstrap.min.css';

export const metadata = {
  title: "Teo's FileServer",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params }) {

  // console.log (params);

  return (
    <>
      <Navbar />
      {children}
    </>
  );
}
